baseURL = "https://jeremyrickard.github.io/"
languageCode = "en-us"
title = "jeremy doing things"
theme = "blackburn"

[params]
  highlightjs = "androidstudio"
  highlightjs_extra_languages = ["yaml","bash"]

[social]
  twitter = "jrrickard"
  github = "jeremyrickard"

